Repository webpack-contrib/file-loader, pull requests merged in 2018-02, with the labels that each got.

#245 chore(package): update `schema-utils` v0.3.0...0.4.5
  package-lock.json
  package.json
  test/__snapshots__/Errors.test.js.snap
Labels: semver: Patch, status: Approved, type: Chore

#244 docs(README): add `regExp` option (`options.regExp`)
  README.md
Labels: pr_action: Review, semver: Patch, status: Pending, type: Documentation

#246 fix(index): don't concat `options.outputPath` and `options.publicPath`
  src/index.js
  test/options/__snapshots__/outputPath.test.js.snap
  test/options/__snapshots__/publicPath.test.js.snap
  test/options/outputPath.test.js
  test/options/publicPath.test.js
Labels: pr_action: Review, priority: 4 (important), severity: 4 (inconvenient), type: Bug

#253 fix(index): handle protocol URL's correctly (`options.publicPath`)
  src/index.js
  test/options/__snapshots__/publicPath.test.js.snap
  test/options/publicPath.test.js
Labels: semver: Patch, status: Approved, type: Bug

#254 fix(index): use `path.posix` for platform consistency
  src/index.js
Labels: semver: Patch, status: Approved, type: Bug

#255 fix(package): add `webpack >= 4` (`peerDependencies`)
  package.json
Labels: semver: Patch, status: Approved, type: Bug
